### PR TITLE
Adding some customizations

### PR DESCRIPTION
**Pull request by loicallsoftware**
Hi,
Here my pull request : 
- Able to custom your navbar and sidebar with navbar_class and sidebar_class in admin_lte_yaml
- Wrap content-header row in a content_header block

Thanks for your accept.
Regards,
Loïc

### CODE REVIEW

**Comment by kevinpapst** [comment]
Thank you @loicallsoftware 👍  
At a first glance this looks good, but ... please add some docs for the next user:
https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/bundle_options.md
https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/layout.md#layout-blocks
then I will give it a try.

**Comment by loicallsoftware** [comment]
Hi @kevinpapst . Ok, I will make a new pull request now. Because I think I can't update it !?

**Comment by kevinpapst** [comment]
Sure you can and you did with your last push 👍

**Comment by kevinpapst** [comment]
Ignore the failure, it is not related to your change!

**Comment by loicallsoftware** [comment]
Hoo yes, OK, I didn't know that. Thank you ;-)
Hope my documentation updates are well. Let me know..
Thanks for your good work on this project.
Loïc

**Comment by loicallsoftware** [comment]
Hi @kevinpapst , are you OK to merge it ? Or, are there something I have to do ?

**Comment by kevinpapst** [comment]
This here is a tiny side-project and changes like yours take a long time to properly review.
It works for you, but I want to test it with 3 projects of mine. 

> Or, are there something I have to do

Yes: wait 😁 I will come back to it.

**Comment by kevinpapst** [comment]
Closing: I will archive this repo now

**Pull request closed without merging**
