### PR TITLE
add .editorconfig file

### PR DESCRIPTION
**Pull request by gggeek**
## Description
Add an editorconfig file

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] I updated the documentation (see [here](https://github.com/kevinpapst/AdminLTEBundle/tree/master/Resources/docs))
- [x] I agree that this code is used in AdminLTEBundle and will be published under the [MIT license](https://github.com/kevinpapst/AdminLTEBundle/blob/master/LICENSE)

### CODE REVIEW

**Comment by gggeek** [comment]
Note: I am still a noobie with nodejs/yarn/webpack.
I am not sure if the files _package.json_ and _yarn.lock_ could also be removed from the 'dist' package, as the building of the AdminLTEBundle bundle assets is done before a release is made and pushed to github, or if they are necessary, as those assets are built when yarn/webpack are run in the top-level project...

**Comment by gggeek** [comment]
I moved the more 'aggressive' trimming and newline settings in a dedicated block, but made it apply to most file types besides php.
In my own experience, I never had troubles with that, as long as there is a minimum of discipline applied throughout the codebase (arguably, one could create even a php file where trailing whitespace is semantically important, but I am sure such practice is universally considered bad)

**Comment by kevinpapst** [comment]
> OK.
> Are you a fan of 'rebase your PRs so that they only show 1 commit', or is it ok to have many commits in your git logs?

I don't care, I use squash merging anyway ;-)

Regarding the rules: I want to avoid that someone pushes a PR that suddenly changes whitespaces ... you are right that it shouldn't make a difference. But this repo was forked and some of the code is pretty old and wasn't touched by myself.

For PHP files I agree that it is safe, as automatic rules via phpcs are already in place. 
Conclusion 😁 please use `[*.php]` only for now.

**Comment by gggeek** [comment]
updated

**Comment by kevinpapst** [comment]
Thank you @gggeek 👍

**Pull request merged**
