### PR TITLE
fix deprecation warnings for SF 4.2

### PR DESCRIPTION
**Pull request by kevinpapst**
**Work in progress**

### CODE REVIEW

**Comment by kevinpapst** [comment]
@jkabat I had to change the service definition, as there were new deprecations. Could you have a look and maybe test it in your application?

**Comment by jkabat** [comment]
sorry for delay, Ill test it today.

**Comment by jkabat** [comment]
@kevinpapst so far it seems to be working fine. Will let you know when I spot something

**Comment by kevinpapst** [comment]
Thanks for the feedback!

**Pull request merged**
