### PR TITLE
Update composer.json to allow php 8

### PR DESCRIPTION
**Pull request by rufinus**
Allow php 8.0

### CODE REVIEW

**Comment by kevinpapst** [comment]
Thanks @rufinus for the idea!
Do you use it with PHP 8? What about the dependencies, are they ready yet?

Can you please update the GitHub action matrix as well:
https://github.com/kevinpapst/AdminLTEBundle/blob/master/.github/workflows/linting.yaml

**Comment by rufinus** [comment]
Yes, I use it with PHP8.0. No problem at all.

The dependencies suffer from the same problem. ^7.1.3 doesnt match >7.99 so you need the --ignore-platform-reqs switch. But you have to start somewhere.

Sure i will update the matrix.

**Comment by torbenbr** [comment]
It's not so easy as you think.

* For php 8 you need min phpunit 8.5 but this use min php 7.2. This bundle use min php7.1.
* php-cs-fixer support php 8 only experimentell
* phpstan/phpstan min version for php 8 is 0.12.33
* knplabs/knp-menu-bundle min version for php 8 is 3.1.0 but this use min php 7.2.

I think a lot of people will cry if you just change that

**Comment by kevinpapst** [comment]
I don't mind bumping min version to PHP 7.3 if necessary (maybe with a new major release though).

The dev dependencies don't really matter, they just have to work. Can be updated to anything you like.

**Comment by torbenbr** [comment]
A new major is a good idea.

@rufinus can you update all dev packages. I will help for testing.

**Comment by kevinpapst** [comment]
I bumped soft requirement for PHP to 7.2 (only in documentation) and relaxed PHP version to `>= 7.1.3`.
Everything works fine in the 7.x and if it doesn't work in 8, someone will complain I guess.

Fixed by #160

**Pull request closed without merging**
