### PR TITLE
Updating to Bootstrap 4 and AdminLTE3. Mostly Complete.

### PR DESCRIPTION
**Pull request by yudhir**
## Description

- Update to Bootstrrap4 and Admin LTE.
- Modify Twig Templates . 
- Modify Bootstrap classes . 
- Remove Incompatible Brand-Logo . Logo is now on the Sidebar . 

## TODO

- [ ] validate if config options still work
  - [ ] theme support
  - [ ] setting to toggle between legacy user menu and navbar link
- [ ] KNP menu testing and adjustments
- [ ] social login styles
- [ ] header navbar links (left from search)
- [ ] add new Flex recipe for changed config
- [ ] complete UPGRADING docs (check TODO)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] I updated the documentation (see [here](https://github.com/kevinpapst/AdminLTEBundle/tree/master/Resources/docs))
- [x] I agree that this code is used in AdminLTEBundle and will be published under the [MIT license](https://github.com/kevinpapst/AdminLTEBundle/blob/master/LICENSE)

### CODE REVIEW

**Comment by kevinpapst** [comment]
Wow, fantastic!!!! Thanks @yudhir 🎉 

I haven't had the time to test it yet due to the holidays, but I'll do that ASAP.
Big thanks, you'll get a lot of friends with that update 😁 I will be back soon with an update.

**Comment by kevinpapst** [comment]
@yudhir you could pull and test my latest changes. The most obvious problems are now solved, but there are still some open TODOs left (I added them to your initial post)

**Comment by yudhir** [comment]
Woo!

**Comment by kevinpapst** [comment]
I merged the current status and will do further work on a branch in this repository.
Should be easier for all folks to test (I hope someone does...).

**Comment by kevinpapst** [comment]
THANK YOU SO MUCH 👍 🎉 

I will try to get it done by the end of the month. If you want to further support with testing and input, that would be awesome.

**Pull request merged**
